services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: insightstox_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/.venv
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: insightstox_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true # Helps with hot-reloading on Windows
    depends_on:
      - backend
