# Generated by Django 5.2.17 on 2026-08-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('GAINERS', 'Market Gainers'), ('LOSERS', 'Market Losers'), ('ACTIVE', 'Most Active'), ('NEWS', 'Market News')], max_length=20, unique=True)),
                ('payload', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
