# Generated by Django 5.2.17 on 2026-08-07 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registration_method', models.CharField(default='email', max_length=50)),
                ('investment_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_profile', models.CharField(blank=True, max_length=255, null=True)),
                ('financial_goals', models.CharField(blank=True, max_length=255, null=True)),
                ('investment_horizon', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.URLField(blank=True, max_length=500, null=True)),
                ('theme', models.CharField(default='dark', max_length=50)),
                ('dashboard_layout', models.CharField(blank=True, max_length=50, null=True)),
                ('is_ai_suggestion_on', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('browser_type', models.CharField(blank=True, default='Unknown', max_length=255)),
                ('os_type', models.CharField(blank=True, default='Unknown', max_length=255)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_active_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_type', models.CharField(max_length=255)),
                ('browser_type', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=500)),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_type', models.CharField(max_length=255)),
                ('browser_type', models.CharField(max_length=255)),
                ('alert_type', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=500)),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
